apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: foobar-api
  description: API definition of foobar
spec:
  type: openapi
  owner: team-a
  lifecycle: production
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: foobar API
    servers:
    - url: https://foobar.127.0.0.1.nip.io
    paths:
      /:
        get:
          summary: Returns hello
